version: '3.8'

services:
  web:
    build: .
    command: gunicorn stock_analysis_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stock_db
      - POSTGRES_USER=stock_user
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:6

volumes:
  postgres_data:
