# Generated by Django 5.0.2 on 2024-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
