# Generated by Django 5.0.2 on 2024-10-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='HOSE', max_length=50),
        ),
    ]
