# Generated by Django 5.0.2 on 2024-10-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='percent_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
