# Generated by Django 5.0.2 on 2024-10-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0002_alter_stock_change_alter_stock_current_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at']},
        ),
    ]
