# Generated by Django 5.0.2 on 2024-10-25 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0002_alter_stock_exchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='stocks',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstockholding',
            name='portfolio',
        ),
        migrations.AlterUniqueTogether(
            name='userstockholding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userstockholding',
            name='stock',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'stock')},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='historicaldata',
            unique_together={('stock', 'date')},
        ),
        migrations.DeleteModel(
            name='StockData',
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
        migrations.DeleteModel(
            name='UserPortfolio',
        ),
        migrations.DeleteModel(
            name='UserStockHolding',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='stocks',
        ),
    ]
