# Generated by Django 5.1.2 on 2024-10-24 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0002_alter_stock_id_alter_stockdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.FloatField()),
                ('change', models.FloatField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
