# Generated by Django 5.0.2 on 2024-10-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0004_remove_stock_company_name_remove_stock_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='volume',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='historicaldata',
            unique_together={('stock', 'date')},
        ),
    ]
