# Generated by Django 5.0.2 on 2024-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0005_stock_last_updated_alter_historicaldata_volume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldata',
            options={},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='close_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='open_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='percent_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='historicaldata',
            index=models.Index(fields=['stock', 'date'], name='stock_analy_stock_i_72a427_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldata',
            index=models.Index(fields=['date', 'close_price'], name='stock_analy_date_749709_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol', 'exchange'], name='stock_analy_symbol_a50f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['updated_at', 'exchange'], name='stock_analy_updated_683fdd_idx'),
        ),
    ]
